# 声明镜像来源为node:12.16.1
FROM node:12.16.1

# 声明工作目录
WORKDIR /web/

# 拷贝web项目到当前工作目录
COPY vue_base/ .

# 通过npm下载cnpm
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org

# 使用cnpm进行安装依赖
RUN cnpm install || npm install

# 使用npm run build命令打包web项目
RUN npm run build

# ======= 以下为多阶段构建 =======

# 声明镜像来源为nginx:alpine, alpine 镜像小
FROM nginx:alpine

# 镜像编写者及邮箱
LABEL MAINTAINER="hvag@qq.com"

# 从.docker-compose/nginx/conf.d/目录拷贝my.conf到容器内的/etc/nginx/conf.d/my.conf
#COPY nginx/conf.d/my.conf /etc/nginx/conf.d/my.conf
COPY nginx/nginx_vue.conf /etc/nginx/nginx.conf

# 从第一阶段进行拷贝文件
COPY --from=0 /web/dist /usr/share/nginx/html